name: Case Notification

on:
  push:
    branches: [ main ]
  schedule:
  - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install bs4
        pip install requests
        pip install python-dotenv
        pip install datetime
        pip install schedule

    - name: Create dot env file
      run: |
        touch .env
        echo "LINE_TOKEN_MY=${{ 'UuEhXjvcWwSCMw2krFdgtnAeDJ1phXP5XgAZKHo4XvT' }}" >> .env
    - name: Case_Notify_P.py
      run: |
        python Case_Notify_P.py