name: Case Notification

on:
  push:
      branches: [ main ]
  schedule:
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install bs4
        pip install requests
        pip install datetime
        pip install schedule
        pip install python-dotenv

    - name: Notify.py
      env:
        LINE_TOKEN_F=${{ secrets.LINE_TOKEN_F }}
        LINE_TOKEN_Y=${{ secrets.LINE_TOKEN_Y }}
        LINE_TOKEN_N=${{ secrets.LINE_TOKEN_N }}
        LINE_TOKEN_GM=${{ secrets.LINE_TOKEN_GM }}
      run: |
        python Notify.py